### ISSUE TITLE
Add info on  how to include custom libraries

### ISSUE THREAD

**Issue by ftjuh** [ChrisMicro/ArduinoOnPc#10]
Hi Chris,

thank you so much for your awesome project! It is exactly what I was looking for for trying out different CBOR libraries and it works like a charm!

Just one quick suggestion: It is kind of self explanatory after some trial and error, but to make it easier for others you could include info on how to include other (non hardware dependent) libraries: copy them to the /libraries folder, copy the Makefile of one of the examples to your own sketch's folder, and add the relative path to the include file, including "src" if needed, e.g. like this: ARDUINO_LIBS += YACL/src

Thanks again
Jan

**Comment by ChrisMicro** [comment]
Hi Jan,
thank you for your valuable hint. I just added your comments to the readme so it should help other users.
Have a nice day,
Christoph
