### ISSUE TITLE
Is serial input possible?

### ISSUE THREAD

**Issue by marcmerlin** [ChrisMicro/ArduinoOnPc#4]
Hi,

I use a fork of your code which emulates FastLED instead of a tft, but ultimately works similarly:
https://github.com/MarcFork/FastLEDonPc

One thing I am however missing quite a bit is serial input. I use serial output like everyone else, but I also require input to control demo code in various ways.
I haven't been able to get serial reading working. Is it supposed to work, or known not implemented?
I use
```
if (Serial.available()) readchar = Serial.read();
```

**Comment by ChrisMicro** [comment]
Hi,
the serial input is the keyboard.
Here I made an example which should answer all your questions:
[SerialInput](https://github.com/ChrisMicro/ArduinoOnPc/blob/master/examples/SerialInput/SerialInput.ino)

**Comment by marcmerlin** [comment]
Thanks, I now see that you have much more updated code than @benpicco in https://github.com/benpicco/FastLEDonPc/commits/master
I'll see if I can port my code on top of yours since I now support tfts as a backend, so it should be easy.
I tried your serial code and while you're right that needing to type NL is a slight drawback, it's not a big deal for my use, thanks for your quick answer.
